-- ============================================================================
-- Migration : renommage du schéma en anglais (stock_management)
-- Ancien schéma (français) -> Nouveau schéma (anglais)
-- ----------------------------------------------------------------------------
-- utilisateurs     -> users
-- produits         -> products
-- fournisseurs     -> suppliers
-- mouvements_stock -> stock_movements
--
-- Colonnes renommées :
--   users:         nom_complet->full_name, actif->active
--   products:      nom->name, categorie->category, quantite_stock->stock_quantity,
--                  seuil_min->min_threshold, prix_unitaire->unit_price,
--                  date_creation->created_date, date_modification->updated_date
--   suppliers:     nom->name, telephone->phone, adresse->address,
--                  date_creation->created_date
--   stock_movements: produit_id->product_id, fournisseur_id->supplier_id,
--                  destinataire->recipient, motif->reason,
--                  reference_externe->external_reference,
--                  prix_unitaire->unit_price, utilisateur_id->user_id,
--                  date_mouvement->movement_date
--
-- Valeurs d'énumération mappées :
--   role:  GESTIONNAIRE -> MANAGEMENT
--   type:  ENTREE -> IN,  SORTIE -> OUT
-- ============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- 1. Création des nouvelles tables (structure anglaise)
-- ---------------------------------------------------------------------------
CREATE TABLE users (
    id         bigint generated by default as identity primary key,
    username   varchar(50)  not null unique,
    password   varchar(255) not null,
    full_name  varchar(100) not null,
    role       varchar(20)  not null,
    active     boolean      not null
);

CREATE TABLE products (
    id             bigint generated by default as identity primary key,
    reference      varchar(50)  not null unique,
    name           varchar(100) not null,
    description    varchar(255),
    category       varchar(50)  not null,
    stock_quantity integer      not null,
    min_threshold  integer      not null,
    unit_price     double precision not null,
    created_date   timestamp    not null,
    updated_date   timestamp
);

CREATE TABLE suppliers (
    id          bigint generated by default as identity primary key,
    nif         varchar(50) unique,
    name        varchar(100),
    phone       varchar(20),
    address     varchar(255),
    created_date timestamp not null
);

CREATE TABLE stock_movements (
    id                bigint generated by default as identity primary key,
    product_id        bigint not null,
    type              varchar(10) not null,
    supplier_id       bigint,
    recipient         varchar(150),
    quantity          integer not null,
    reason            varchar(255),
    external_reference varchar(100),
    unit_price        double precision not null,
    user_id           bigint not null,
    movement_date     timestamp not null
);

ALTER TABLE stock_movements
    ADD CONSTRAINT fk_stock_movements_product FOREIGN KEY (product_id) REFERENCES products(id);
ALTER TABLE stock_movements
    ADD CONSTRAINT fk_stock_movements_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id);
ALTER TABLE stock_movements
    ADD CONSTRAINT fk_stock_movements_user FOREIGN KEY (user_id) REFERENCES users(id);

-- ---------------------------------------------------------------------------
-- 2. Copie des données (IDs conservés pour préserver les relations)
-- ---------------------------------------------------------------------------
INSERT INTO users (id, username, password, full_name, role, active)
SELECT id, username, password, nom_complet,
       CASE WHEN role = 'GESTIONNAIRE' THEN 'MANAGEMENT' ELSE role END,
       actif
FROM utilisateurs;

INSERT INTO products
    (id, reference, name, description, category, stock_quantity,
     min_threshold, unit_price, created_date, updated_date)
SELECT id, reference, nom, description, categorie, quantite_stock,
       seuil_min, prix_unitaire, date_creation, date_modification
FROM produits;

INSERT INTO suppliers (id, nif, name, phone, address, created_date)
SELECT id, nif, nom, telephone, adresse, date_creation
FROM fournisseurs;

INSERT INTO stock_movements
    (id, product_id, type, supplier_id, recipient, quantity,
     reason, external_reference, unit_price, user_id, movement_date)
SELECT id, produit_id,
       CASE WHEN type = 'ENTREE' THEN 'IN' ELSE 'OUT' END,
       fournisseur_id, destinataire, quantite,
       motif, reference_externe, prix_unitaire, utilisateur_id, date_mouvement
FROM mouvements_stock;

-- ---------------------------------------------------------------------------
-- 3. Réinitialisation des séquences (identity) après import des IDs explicites
-- ---------------------------------------------------------------------------
SELECT setval(pg_get_serial_sequence('users',           'id'), (SELECT max(id) FROM users));
SELECT setval(pg_get_serial_sequence('products',        'id'), (SELECT max(id) FROM products));
SELECT setval(pg_get_serial_sequence('suppliers',       'id'), (SELECT max(id) FROM suppliers));
SELECT setval(pg_get_serial_sequence('stock_movements', 'id'), (SELECT max(id) FROM stock_movements));

-- ---------------------------------------------------------------------------
-- 4. Vérification (doit renvoyer les mêmes compteurs que l'ancien schéma)
-- ---------------------------------------------------------------------------
SELECT 'users' AS table, count(*) FROM users
UNION ALL SELECT 'products', count(*) FROM products
UNION ALL SELECT 'suppliers', count(*) FROM suppliers
UNION ALL SELECT 'stock_movements', count(*) FROM stock_movements;

-- ---------------------------------------------------------------------------
-- 5. Suppression de l'ancien schéma (après validation de la copie)
-- ---------------------------------------------------------------------------
DROP TABLE mouvements_stock;
DROP TABLE produits;
DROP TABLE fournisseurs;
DROP TABLE utilisateurs;

COMMIT;
