-- ============================================================================
-- V1 : schéma initial, généré à partir des entités JPA (source de vérité).
--
-- Sur la base existante (Railway), sans historique Flyway, « baseline-on-migrate
-- = true » crée un baseline à la version 1 : ce script n'est donc exécuté que
-- sur une base fraîche. ddl-auto est passé à « validate » : Hibernate ne crée
-- ni ne modifie plus rien.
--
-- Historique hors dépôt (déjà appliqué en production, conservé pour référence) :
--   D:\Montage Gold Project\db\migrate-to-english.sql
--   D:\Montage Gold Project\db\migrate-category-relation.sql
--   D:\Montage Gold Project\db\migrate-backfill-reprise.sql
-- ============================================================================

CREATE TABLE users (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username             varchar(50)   NOT NULL UNIQUE,
    password             varchar(255)  NOT NULL,
    full_name            varchar(100)  NOT NULL,
    role                 varchar(20)   NOT NULL,
    active               boolean       NOT NULL,
    must_change_password boolean       NOT NULL
);

CREATE TABLE categories (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar(50) NOT NULL UNIQUE,
    created_date timestamp   NOT NULL
);

CREATE TABLE products (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference      varchar(50)     NOT NULL UNIQUE,
    name           varchar(100)    NOT NULL,
    description    varchar(255),
    category_id    bigint REFERENCES categories (id),
    stock_quantity integer         NOT NULL,
    min_threshold  integer         NOT NULL,
    unit_price     double precision NOT NULL,
    created_date   timestamp       NOT NULL,
    updated_date   timestamp
);

CREATE TABLE suppliers (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nif          varchar(50) UNIQUE,
    name         varchar(100),
    phone        varchar(20),
    address      varchar(255),
    created_date timestamp NOT NULL
);

CREATE TABLE stock_movements (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id         bigint        NOT NULL REFERENCES products (id),
    type               varchar(10)   NOT NULL,
    supplier_id        bigint REFERENCES suppliers (id),
    recipient          varchar(150),
    quantity           integer       NOT NULL,
    reason             varchar(255),
    external_reference varchar(100),
    unit_price         double precision NOT NULL,
    user_id            bigint        NOT NULL REFERENCES users (id),
    reverses_id        bigint REFERENCES stock_movements (id),
    movement_date      timestamp     NOT NULL
);

-- Index pour les listes paginées (tri par date décroissante) et le détail produit.
CREATE INDEX idx_stock_movements_movement_date ON stock_movements (movement_date DESC);
CREATE INDEX idx_stock_movements_product_id ON stock_movements (product_id);
