-- ============================================================================
-- V2 : alignement idempotent du schéma existant sur les entités JPA.
--
-- V1 couvre les bases fraîches. V2 ne s'applique qu'aux bases historiques
-- initialisées avant Flyway (baseline à la version 1) : il crée uniquement
-- ce qui manque (tables, colonnes, contraintes, index), sans jamais modifier
-- l'existant, afin que « ddl-auto: validate » passe sur un déploiement
-- antérieur à la refacto. Sur une base fraîche, tout est no-op.
--
-- La fonction _ensure_col est supprimée en fin de script.
-- ============================================================================

-- 1. Tables potentiellement absentes -----------------------------------------

CREATE TABLE IF NOT EXISTS users (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username             varchar(50),
    password             varchar(255),
    full_name            varchar(100),
    role                 varchar(20),
    active               boolean,
    must_change_password boolean
);

CREATE TABLE IF NOT EXISTS categories (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar(50),
    created_date timestamp
);

CREATE TABLE IF NOT EXISTS products (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference      varchar(50),
    name           varchar(100),
    description    varchar(255),
    category_id    bigint,
    stock_quantity integer,
    min_threshold  integer,
    unit_price     double precision,
    created_date   timestamp,
    updated_date   timestamp
);

CREATE TABLE IF NOT EXISTS suppliers (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nif          varchar(50),
    name         varchar(100),
    phone        varchar(20),
    address      varchar(255),
    created_date timestamp
);

CREATE TABLE IF NOT EXISTS stock_movements (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id         bigint,
    type               varchar(10),
    supplier_id        bigint,
    recipient          varchar(150),
    quantity           integer,
    reason             varchar(255),
    external_reference varchar(100),
    unit_price         double precision,
    user_id            bigint,
    reverses_id        bigint,
    movement_date      timestamp
);

-- 2. Colonnes manquantes : ajout + valeur par défaut + contrainte NOT NULL ---

CREATE OR REPLACE FUNCTION _ensure_col(
    p_table text, p_col text, p_type text, p_default text, p_not_null boolean
) RETURNS void LANGUAGE plpgsql AS $fn$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = p_table AND column_name = p_col
    ) THEN
        EXECUTE format('ALTER TABLE %I ADD COLUMN %I %s', p_table, p_col, p_type);
    END IF;
    IF p_default IS NOT NULL THEN
        EXECUTE format('ALTER TABLE %I ALTER COLUMN %I SET DEFAULT %s', p_table, p_col, p_default);
        EXECUTE format('UPDATE %I SET %I = %s WHERE %I IS NULL', p_table, p_col, p_default, p_col);
    END IF;
    IF p_not_null THEN
        EXECUTE format('ALTER TABLE %I ALTER COLUMN %I SET NOT NULL', p_table, p_col);
    END IF;
END
$fn$;

-- users
SELECT _ensure_col('users', 'username', 'varchar(50)', '''''', true);
SELECT _ensure_col('users', 'password', 'varchar(255)', '''''', true);
SELECT _ensure_col('users', 'full_name', 'varchar(100)', '''''', true);
SELECT _ensure_col('users', 'role', 'varchar(20)', '''''', true);
SELECT _ensure_col('users', 'active', 'boolean', 'true', true);
SELECT _ensure_col('users', 'must_change_password', 'boolean', 'true', true);

-- categories
SELECT _ensure_col('categories', 'name', 'varchar(50)', '''''', true);
SELECT _ensure_col('categories', 'created_date', 'timestamp', 'now()', true);

-- products
SELECT _ensure_col('products', 'reference', 'varchar(50)', '''''', true);
SELECT _ensure_col('products', 'name', 'varchar(100)', '''''', true);
SELECT _ensure_col('products', 'description', 'varchar(255)', NULL, false);
SELECT _ensure_col('products', 'category_id', 'bigint', NULL, false);
SELECT _ensure_col('products', 'stock_quantity', 'integer', '0', true);
SELECT _ensure_col('products', 'min_threshold', 'integer', '0', true);
SELECT _ensure_col('products', 'unit_price', 'double precision', '0', true);
SELECT _ensure_col('products', 'created_date', 'timestamp', 'now()', true);
SELECT _ensure_col('products', 'updated_date', 'timestamp', NULL, false);

-- suppliers
SELECT _ensure_col('suppliers', 'nif', 'varchar(50)', NULL, false);
SELECT _ensure_col('suppliers', 'name', 'varchar(100)', NULL, false);
SELECT _ensure_col('suppliers', 'phone', 'varchar(20)', NULL, false);
SELECT _ensure_col('suppliers', 'address', 'varchar(255)', NULL, false);
SELECT _ensure_col('suppliers', 'created_date', 'timestamp', 'now()', true);

-- stock_movements
SELECT _ensure_col('stock_movements', 'product_id', 'bigint', NULL, true);
SELECT _ensure_col('stock_movements', 'type', 'varchar(10)', '''''', true);
SELECT _ensure_col('stock_movements', 'supplier_id', 'bigint', NULL, false);
SELECT _ensure_col('stock_movements', 'recipient', 'varchar(150)', NULL, false);
SELECT _ensure_col('stock_movements', 'quantity', 'integer', '0', true);
SELECT _ensure_col('stock_movements', 'reason', 'varchar(255)', NULL, false);
SELECT _ensure_col('stock_movements', 'external_reference', 'varchar(100)', NULL, false);
SELECT _ensure_col('stock_movements', 'unit_price', 'double precision', '0', true);
SELECT _ensure_col('stock_movements', 'user_id', 'bigint', NULL, true);
SELECT _ensure_col('stock_movements', 'reverses_id', 'bigint', NULL, false);
SELECT _ensure_col('stock_movements', 'movement_date', 'timestamp', 'now()', true);

-- 3. Clés étrangères (idempotent, identification par relations) ---------------

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE contype = 'f'
          AND conrelid = 'products'::regclass
          AND confrelid = 'categories'::regclass
    ) THEN
        ALTER TABLE products ADD CONSTRAINT fk_products_category
            FOREIGN KEY (category_id) REFERENCES categories (id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE contype = 'f'
          AND conrelid = 'stock_movements'::regclass
          AND confrelid = 'products'::regclass
          AND pg_get_constraintdef(oid) LIKE '%(product_id)%'
    ) THEN
        ALTER TABLE stock_movements ADD CONSTRAINT fk_movements_product
            FOREIGN KEY (product_id) REFERENCES products (id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE contype = 'f'
          AND conrelid = 'stock_movements'::regclass
          AND confrelid = 'suppliers'::regclass
    ) THEN
        ALTER TABLE stock_movements ADD CONSTRAINT fk_movements_supplier
            FOREIGN KEY (supplier_id) REFERENCES suppliers (id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE contype = 'f'
          AND conrelid = 'stock_movements'::regclass
          AND confrelid = 'users'::regclass
          AND pg_get_constraintdef(oid) LIKE '%(user_id)%'
    ) THEN
        ALTER TABLE stock_movements ADD CONSTRAINT fk_movements_user
            FOREIGN KEY (user_id) REFERENCES users (id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE contype = 'f'
          AND conrelid = 'stock_movements'::regclass
          AND confrelid = 'stock_movements'::regclass
    ) THEN
        ALTER TABLE stock_movements ADD CONSTRAINT fk_movements_reverses
            FOREIGN KEY (reverses_id) REFERENCES stock_movements (id);
    END IF;
END $$;

-- 4. Uniques (présence d'un index sur la colonne, indépendamment du nom) -----

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_indexes
        WHERE schemaname = 'public' AND tablename = 'users'
          AND indexdef LIKE '%(username)%'
    ) THEN
        ALTER TABLE users ADD CONSTRAINT uq_users_username UNIQUE (username);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_indexes
        WHERE schemaname = 'public' AND tablename = 'products'
          AND indexdef LIKE '%(reference)%'
    ) THEN
        ALTER TABLE products ADD CONSTRAINT uq_products_reference UNIQUE (reference);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_indexes
        WHERE schemaname = 'public' AND tablename = 'categories'
          AND indexdef LIKE '%(name)%'
    ) THEN
        ALTER TABLE categories ADD CONSTRAINT uq_categories_name UNIQUE (name);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_indexes
        WHERE schemaname = 'public' AND tablename = 'suppliers'
          AND indexdef LIKE '%(nif)%'
    ) THEN
        ALTER TABLE suppliers ADD CONSTRAINT uq_suppliers_nif UNIQUE (nif);
    END IF;
END $$;

-- 5. Index de listes paginées -----------------------------------------------

CREATE INDEX IF NOT EXISTS idx_stock_movements_movement_date
    ON stock_movements (movement_date DESC);
CREATE INDEX IF NOT EXISTS idx_stock_movements_product_id
    ON stock_movements (product_id);

-- 6. Nettoyage de la fonction utilitaire -------------------------------------

DROP FUNCTION IF EXISTS _ensure_col(text, text, text, text, boolean);
